// Generated by CoffeeScript 1.9.3
(function() {
  var handler, through2;

  through2 = require('through2');

  handler = function(data) {
    var escape, fileJSON, i, index, key, keys, len, val;
    keys = Object.keys(data).sort();
    fileJSON = "{\n";
    for (index = i = 0, len = keys.length; i < len; index = ++i) {
      key = keys[index];
      if (data[key].replace) {
        escape = data[key].replace(/"/g, "\\\"");
        val = "  \"" + key + "\": \"" + escape + "\"";
      } else {
        escape = handler(data[key]);
        val = "  \"" + key + "\": " + escape;
      }
      if (index !== keys.length - 1) {
        val += ",";
      }
      fileJSON += val + "\n";
    }
    fileJSON += "}";
    return fileJSON;
  };

  module.exports = function() {
    return through2.obj(function(file, enc, cb) {
      var ctx, e;
      if (file.isNull()) {
        return cb(null, file);
      }
      try {
        ctx = file.contents.toString('utf8');
        file.contents = new Buffer(handler(JSON.parse(ctx)));
        return cb(null, file);
      } catch (_error) {
        e = _error;
        return cb(e, file);
      }
    });
  };

}).call(this);
